### ISSUE TITLE
Add Django admin integration

### ISSUE THREAD

**Issue by MarkusH** [MarkusH/django-osm-field#3]

**Comment by int-ua** [comment]
With `django-grappelli` field class is just `.location`.

I also changed `js` to 

```
js = (
    'https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js',
)
```

**Comment by int-ua** [comment]
It stopped working after upgrade to `0.3.0` and I can't understand why.

**Comment by blag** [comment]
@int-ua: Can you give me more information? Like copy/paste the files you use on your admin page, the HTML from your admin page, and anything else that might be relevant? I can't really help you without any additional information.

**Comment by int-ua** [comment]
Sorry, it was completely my fault, somehow I've defined `widgets` not in a `Meta` subclass of `ModelForm` but on itsefl and it had no effect. It's completely functional after fixing this error.

**Comment by blag** [comment]
@int-ua No worries, we all make mistakes. I'm glad you got it working again! 😄

**Comment by blag** [comment]
This seems to be working just fine for. I'm closing this unless somebody has a more specific issue.
